language: haskell
ghc:
  - "8.8.2"
before_install:
  - sudo apt-get -y install libgc-dev clang
install:
  - cabal install cabal-install
  - cabal install hspec-discover
  - cabal new-configure
  - cabal new-build --dep -j2 all

script:
 - cabal new-build all
 - cabal new-test all
 - cabal new-haddock all
 - cabal install
 - ./test.sh
