language: haskell

dist: xenial

git:
  depth: 5

cabal: "3.2"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  - "$TRAVIS_BUILD_DIR/dist-newstyle"

matrix:
  include:
  - ghc: 8.8.3

addons:
  apt:
    update: true
    packages:
      - libgc-dev

install:
  - |
    ghc --version
    cabal --version
    cabal new-update
    cabal new-build --enable-tests --enable-benchmarks

script:
  - |
    cabal new-test --enable-tests
    ./test.sh