sudo: true
language: haskell

dist: xenial

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  - "$TRAVIS_BUILD_DIR/dist-newstyle"

matrix:
  include:
  # Stack
  - ghc: 8.8.2
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    update: true
    packages:
      - libgc-dev
      - llvm-9-dev

install:
  - |
    llvm-config --version
    # install stack
    curl -sSL https://get.haskellstack.org/ | sh

    # build project with stack
    stack --version
    stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - |
    stack test --system-ghc
    ./test.sh
