sudo: true
language: haskell

dist: xenial

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
  - "$TRAVIS_BUILD_DIR/dist-newstyle"

matrix:
  include:

  # # Cabal
  # - ghc: 8.8.2

  # Stack
  - ghc: 8.8.2
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

# before_install:
  # - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main" | sudo tee -a /etc/apt/sources.list
  # - echo "deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main" | sudo tee -a /etc/apt/sources.list
  # - sudo apt-get update
  # - sudo apt-get -y install libgc-dev llvm-9-dev --allow-unauthenticated

addons:
  apt:
    sources:
      - sourceline: deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main
      - sourceline: deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main
    update: true
    packages:
      - libgc-dev
      - llvm-9-dev

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test --enable-tests
    else
      stack test --system-ghc
      ./test.sh
    fi