language: haskell
before_install:
  - sudo apt-get -y install libgc-dev clang
script:
 - cabal new-build -w ${HC} all
 - cabal new-test -w ${HC} all
 - cabal new-haddock -w ${HC} all
 - cabal install
 - ./test.sh
