[package]
name = "malgo"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
rowan = "0.15.6"
tracing = "0.1.35"
tracing-subscriber = "0.3.15"
