name: malgo
version: '1.0.0.0'
category: Compilers/Interpreters
author: Yuya Kono
maintainer: takohati0821@gmail.com
copyright: 2017 Yuya Kono
license: BSD3
github: takoeight0821/malgo
extra-source-files:
- README.md

library:
  source-dirs: src
  build-tools:
  - happy
  ghc-options: -Wall
  dependencies:
  - base >=4.7 && <5
  - array
  - bytestring
  - containers
  - directory
  - filepath
  - flow
  - generic-lens
  - lens
  - llvm-hs-pretty
  - llvm-hs-pure
  - mtl
  - optparse-applicative
  - parsec
  - prettyprinter
  - protolude
  - text

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
  - base
  - malgo
  - mtl
  - parsec
  - bytestring
  - containers
  - llvm-hs-pretty

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - malgo
    - mtl
    - parsec
    - hspec
