name: malgo
version: 0.2.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2021 Yuya Kono"

build-type: Simple

dependencies:
  - aeson
  - base
  - binary
  - binary-instances
  - bytestring
  - containers
  - data-fix
  - deriving-compat
  - directory
  - exceptions
  - extra
  - filepath
  - hashable
  - lens
  - generic-lens
  - llvm-hs
  - llvm-hs-pure
  - megaparsec
  - microlens-platform
  - mtl
  - optparse-applicative
  - parser-combinators
  - pretty
  - pretty-simple
  - recursion-schemes
  - relude >= 1.0.0.0
  - string-conversions
  - text
  - transformers
  - uniplate
  - unordered-containers
  - witherable
  - lsp
  - lsp-types

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

  - -Wno-name-shadowing
  - -Wmissing-deriving-strategies

  - -optP-Wno-nonportable-include-path
  - -j
  - +RTS -A128m -n2m -qg -RTS

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns

library:
  source-dirs: src

executables:
  malgo:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - malgo

tests:
  malgo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - malgo
    - typed-process
    - hspec
