name:                malgo
version:             1.0.0.0
github:              "malgo-lang/malgo"
license:             BSD3
author:              "KONO Yuya"
maintainer:          "takohati0821@gmail.com"
copyright:           "2023 KONO Yuya"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/malgo-lang/malgo#readme>

dependencies:
- base >= 4.7
- bytestring
- containers
- diagnose
- flow
- lens
- mtl
- transformers
- parsec
- prettyprinter
- string-conversions
- text
- text-icu
- unordered-containers
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

language: GHC2021

default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DerivingStrategies
  - FunctionalDependencies
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - StrictData
  - TypeFamilies
  - ViewPatterns
  - OverloadedRecordDot
  - NoFieldSelectors
  - TypeData

library:
  source-dirs: src

executables:
  malgo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - malgo

tests:
  malgo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - malgo
    - tasty
    - tasty-hunit
    - tasty-golden
    build-tool-depends:
    - tasty-discover:tasty-discover
