name: malgo
version: '1.0.0.0'
category: Compilers/Interpreters
author: Yuya Kono
maintainer: takohati0821@gmail.com
copyright: 2017-2018 Yuya Kono
license: BSD3
github: takoeight0821/malgo
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude
- StrictData
- OverloadedStrings

library:
  source-dirs: src
  build-tools:
  - happy
  dependencies:
  - base >=4.7 && <5
  - array
  - lens
  - llvm-hs-pretty
  - llvm-hs-pure
  - mtl
  - optparse-applicative
  - parsec
  - pretty
  - outputable
  - text
  - universum
  - containers

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
  - base
  - malgo
  - mtl
  - parsec
  - containers
  - text
  - llvm-hs-pretty
  - universum

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base
    - universum
    - malgo
    - mtl
    - parsec
    - hspec
