name: malgo
version: 3.0.0
github: "takoeight0821/malgo"
license: BSD-3-Clause
author: "Yuya KONO"
maintainer: "takohati0821@gmail.com"
copyright: "2024 Yuya KONO"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/takoeight0821/malgo#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - string-conversions
  - effectful
  - effectful-core
  - text
  - log-base
  - log-effectful
  - pretty-simple
  - lens
  - megaparsec
  - parser-combinators
  - hspec
  - hspec-golden
  - s-cargot
  - filepath

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wredundant-constraints
  - -Wno-name-shadowing

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedRecordDot
  - NoFieldSelectors
  - DuplicateRecordFields
  - BlockArguments
  - FunctionalDependencies
  - RecordWildCards

language: GHC2024

library:
  source-dirs: src

executables:
  malgo-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - malgo

tests:
  malgo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - malgo
