name: malgo
version: 1.0.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2024 Yuya Kono"

build-type: Simple

dependencies:
  - Glob
  - aeson
  - base
  - bytestring
  - containers
  - directory
  - effectful
  - effectful-core
  - exceptions
  - extra
  - filepath
  - generic-data
  - hashable
  - io-streams
  - lens
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - path
  - pretty-simple
  - prettyprinter
  - s-cargot
  - store
  - string-conversions
  - text
  - transformers
  - unliftio
  - unordered-containers
  - witherable
  - text-icu

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

  - -Wno-name-shadowing
  - -Wmissing-deriving-strategies
  - -Wmissing-export-lists

  - -optP-Wno-nonportable-include-path

language: GHC2021

default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DerivingStrategies
  - FunctionalDependencies
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - StrictData
  - TypeFamilies
  - ViewPatterns
  - OverloadedRecordDot
  - NoFieldSelectors
  - TypeData
  - Strict

library:
  source-dirs: src

executables:
  malgo:
    main: Main.hs
    source-dirs: app/malgo/
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - malgo

tests:
  malgo-test:
    defaults: hspec/hspec@main
    dependencies:
      - malgo
      - typed-process
      - hspec
      - hspec-core
      - prettyprinter
      - silently
      - time
      - hspec-golden >= 0.2.2.0
      - string-conversions
      - pretty-simple
