name: malgo
version: 0.2.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2021 Yuya Kono"

build-type: Simple

dependencies:
  - Glob
  - aeson
  - base
  - binary
  - binary-instances
  - bytestring
  - containers
  - directory
  - extra
  - filepath
  - hashable
  - lens
  - llvm-hs
  - llvm-hs-pure
  - lsp
  - lsp-types
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - pretty
  - string-conversions
  - text
  - transformers
  - unordered-containers
  - witherable
  - diagnose >= 2.4.0
  - generic-data
  - syb
  - unliftio

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

  - -Wno-name-shadowing
  - -Wmissing-deriving-strategies
  - -Wmissing-export-lists

  - -optP-Wno-nonportable-include-path
  - -j
  - +RTS -A128m -n2m -qg -RTS

language: GHC2021

default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DerivingStrategies
  - FunctionalDependencies
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - StrictData
  - TypeFamilies
  - ViewPatterns
  - OverloadedRecordDot
  - NoFieldSelectors

library:
  source-dirs: src

executables:
  malgo:
    main: Main.hs
    source-dirs: app/malgo/
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - malgo

tests:
  malgo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - malgo
      - typed-process
      - hspec
      - prettyprinter
      - silently
      - time

benchmarks:
  malgo-bench:
    main: Main.hs
    source-dirs: benchmarks
    dependencies:
      - malgo
      - typed-process
      - criterion
