ghc-options:
  $everything: -haddock
  llvm-hs: -optcxx -std=c++14
packages:
- koriel/
- malgo/
extra-deps:
- subdirs:
  - llvm-hs
  - llvm-hs-pure
  git: git@github.com:llvm-hs/llvm-hs
  commit: 0c8795a95a8001c424af81a05b8ffacd774e76bd
resolver: lts-18.5
