ghc-options:
  $everything: -haddock
  llvm-hs: -optcxx -std=c++11
packages:
- koriel/
- malgo/
extra-deps:
  - llvm-hs-pretty-0.9.0.0@sha256:b7a5de5f3dd97893d19d2b47af1e4dd8d075a5cf57062180a912d1f3ef1def60,1671
resolver: nightly-2021-02-28
