extra-deps:
- github: llvm-hs/llvm-hs
  subdirs:
    - llvm-hs
    - llvm-hs-pure
  commit: eda85a2bbe362a0b89df5adce0cb65e4e755eac5
  # resolver: lts-18.21
resolver: lts-19.0

ghc-options:
  $everything: -haddock
