ghc-options:
  $everything: -haddock
  llvm-hs: -optcxx -std=c++14
packages:
- koriel/
- malgo/
extra-deps:
  - git: git@github.com:llvm-hs/llvm-hs
    commit: 0c8795a95a8001c424af81a05b8ffacd774e76bd
    subdirs:
      - llvm-hs
      - llvm-hs-pure
resolver:  nightly-2021-08-08
