extra-deps:
  # - github: llvm-hs/llvm-hs
  #   subdirs:
  #     - llvm-hs
  #     - llvm-hs-pure
  #   commit: 789e2b9e8b827d4c5e15b997f16e395fd2259c0f
    # - relude-1.1.0.0
    # - hashable-1.4.0.2
  - github: MuKnIO/llvm-hs
    subdirs:
      - llvm-hs
      - llvm-hs-pure
    commit: fe8fd556e8d2cc028f61d4d7b4b6bf18c456d090
  - lsp-1.5.0.0
  - co-log-core-0.3.1.0@sha256:9794bdedd1391decd0e22bdfe2b11abcb42e6cff7a4531e1f8882890828f4e63,3816


allow-newer: true
resolver: nightly-2022-08-04


ghc-options:
  $everything: -haddock
  malgo: -DSTACK
  malgo-test: -DSTACK
