ghc-options:
  $everything: -haddock
  llvm-hs: -optcxx -std=c++14
extra-deps:
- github: llvm-hs/llvm-hs
  subdirs:
    # - llvm-hs
    - llvm-hs-pure
  commit: 47ed4d900aaa8ed2b74726cfc2eeeeb029a1f165
- github: llvm-hs/llvm-hs-pretty
  commit: 990bb6981f6214d9c1bbf46fd9e9ce5596d3bf30
  # - llvm-hs-pretty-0.9.0.0@sha256:b7a5de5f3dd97893d19d2b47af1e4dd8d075a5cf57062180a912d1f3ef1def60,1671
resolver: lts-18.10