extra-deps:
- github: llvm-hs/llvm-hs
  subdirs:
    - llvm-hs
    - llvm-hs-pure
  commit: 789e2b9e8b827d4c5e15b997f16e395fd2259c0f
- relude-1.1.0.0
- hashable-1.4.0.2
resolver: lts-19.12

ghc-options:
  $everything: -haddock
  malgo: -DSTACK
  malgo-test: -DSTACK
