// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR-0]
	_ = x[EOF-1]
	_ = x[LEFTPAREN-2]
	_ = x[RIGHTPAREN-3]
	_ = x[LEFTBRACE-4]
	_ = x[RIGHTBRACE-5]
	_ = x[LEFTBRACKET-6]
	_ = x[RIGHTBRACKET-7]
	_ = x[COLON-8]
	_ = x[COMMA-9]
	_ = x[DOT-10]
	_ = x[SEMICOLON-11]
	_ = x[SHARP-12]
	_ = x[IDENT-13]
	_ = x[OPERATOR-14]
	_ = x[INTEGER-15]
	_ = x[STRING-16]
	_ = x[SYMBOL-17]
	_ = x[ARROW-18]
	_ = x[BACKARROW-19]
	_ = x[BAR-20]
	_ = x[CASE-21]
	_ = x[DATA-22]
	_ = x[DEF-23]
	_ = x[EQUAL-24]
	_ = x[FN-25]
	_ = x[INFIX-26]
	_ = x[INFIXL-27]
	_ = x[INFIXR-28]
	_ = x[LET-29]
	_ = x[PRIM-30]
	_ = x[TYPE-31]
	_ = x[WITH-32]
}

const _Kind_name = "ERROREOFLEFTPARENRIGHTPARENLEFTBRACERIGHTBRACELEFTBRACKETRIGHTBRACKETCOLONCOMMADOTSEMICOLONSHARPIDENTOPERATORINTEGERSTRINGSYMBOLARROWBACKARROWBARCASEDATADEFEQUALFNINFIXINFIXLINFIXRLETPRIMTYPEWITH"

var _Kind_index = [...]uint8{0, 5, 8, 17, 27, 36, 46, 57, 69, 74, 79, 82, 91, 96, 101, 109, 116, 122, 128, 133, 142, 145, 149, 153, 156, 161, 163, 168, 174, 180, 183, 187, 191, 195}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
