; EBNF for malgo syntax.

nil = ; an empty string

program = decs

decs = {dec}

dec = scdec
    | scann
    | typedec

scdec = ident [params] "=" expr
scann = ident ":" type_scheme

typedec = "type" ident {tyvar} "=" type ; type synonym
        | "data" ident {tyvar} "=" type ; new type with constructor

type_scheme = ["forall" {tyvar} "."] type