; EBNF for malgo syntax.

program = decs

decs = {dec \n}

dec = scdec
    | scann
    | datadec
    | typedec

scdec = ident [params] "=" expr
scann = ident ":" type_scheme

datadec = "data" Lident {tyvar} "=" constructors
typedec = "type" Lident {tyvar} "=" type

type_scheme = ["forall" {tyvar} "."] type

expr = ident ; variable
     | int   ; int literal
     | float ; float literal
     | "True" | "False" ; boolean literal
     | char  ; char literal
     | constructor
     | "let" bind "in" expr
     | expr expr ; application
     | "case" expr "{" { "|" clause } "}" ; pattern match
     | "fun" {ident | "(" ident ":" type ")"} "->" expr

bind = ident [":" type] "=" expr
     | "rec" recbind { "and" recbind }

recbind = ident {ident} [":" type] "=" expr

clause = cons_pat "=>" expr
       | "true" "=>" expr
       | "false" "=>" expr

type = tycon {type} ; type application
     | type "->" type
     | ident        ; type variable

tycon = Lident
