name: malgo
version: 1.0.0.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2021 Yuya Kono"

build-type: Simple

dependencies:
  - base
  - binary
  - binary-instances
  - bytestring
  - containers
  - data-fix
  - deriving-compat
  - directory
  - extra
  - filepath
  - hashable
  - koriel
  - lens
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - pretty
  - text
  - transformers
  - unordered-containers
  - recursion-schemes

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Widentities
  - -Wmissing-deriving-strategies
  - -Wno-name-shadowing
  - -j4
  - +RTS -A128m -n2m -qg -RTS

default-extensions:
  - StrictData

library:
  source-dirs: src

executables:
  malgo:
    main: Main.hs
    source-dirs: app/
    ghc-options:
      - -threaded
    dependencies:
      - malgo
      - shake