name: malgo
version: 1.0.0.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2021 Yuya Kono"

build-type: Simple

dependencies:
  - base
  - binary
  - binary-instances
  - bytestring
  - containers
  - data-fix
  - deriving-compat
  - directory
  - extra
  - filepath
  - hashable
  - koriel
  - lens
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - pretty
  - text
  - transformers
  - unordered-containers
  - recursion-schemes

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

  - -Wno-name-shadowing
  - -Wmissing-deriving-strategies

  - -j4
  - +RTS -A128m -n2m -qg -RTS

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - StrictData

library:
  source-dirs: src

executables:
  malgo:
    main: Main.hs
    source-dirs: app/
    ghc-options:
      - -threaded
    dependencies:
      - malgo
      - shake