name: malgo
version: 1.0.0.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2020 Yuya Kono"

build-type: Simple

dependencies:
  - array
  - base
  - bytestring
  - containers
  - koriel
  - llvm-hs-pure
  - llvm-hs
  - mtl
  - optparse-applicative
  - parsec
  - pretty
  - pretty-simple
  - text
  - transformers
  - vector

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -j4
  - +RTS -A128m -n2m -qg -RTS

default-extensions:
  - StrictData

build-tools:
  - happy

library:
  source-dirs: src

executables:
  malgoc:
    main: Main.hs
    source-dirs: app/
    ghc-options:
      - -threaded
    dependencies:
      - malgo
      - llvm-hs-pretty

tests:
  malgo-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - malgo
      - hspec
