name: malgo
version: 1.0.0.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2021 Yuya Kono"

build-type: Simple

dependencies:
  - aeson
  - base
  - bytestring
  - deriving-compat
  - binary
  - containers
  - directory
  - data-fix
  - filepath
  - extra
  - koriel
  - lens
  - llvm-hs
  - llvm-hs-pretty
  - llvm-hs-pure
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - pretty
  - text
  - transformers

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wno-name-shadowing
  - -j4
  - +RTS -A128m -n2m -qg -RTS

default-extensions:
  - StrictData

library:
  source-dirs: src

executables:
  malgoc:
    main: Main.hs
    source-dirs: app/
    ghc-options:
      - -threaded
    dependencies:
      - malgo
      - llvm-hs-pretty
      - shake