name: koriel
version: 1.0.0.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2020 Yuya Kono"

build-type: Simple

dependencies:
  - aeson
  - base
  - binary
  - bytestring
  - data-fix
  - deriving-compat
  - hashable
  - unordered-containers
  - witherable
  - extra
  - llvm-hs-pure
  - llvm-hs-pretty
  - megaparsec
  - mtl
  - pretty
  - string-conversions
  - text
  - transformers
  - lens

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wno-name-shadowing
  - -j4
  - +RTS -A128m -n2m -qg -RTS

default-extensions:
  - StrictData

library:
  source-dirs: src