name: koriel
version: 1.0.0.0
category: Compilers/Interpreters
github: takoeight0821/malgo
license: BSD3
author: "Yuya Kono"
maintainer: "takohati0821@gmail.com"
copyright: "2017-2020 Yuya Kono"

build-type: Simple

dependencies:
  - array
  - base
  - bytestring
  - containers
  - dlist
  - extra
  - list-predicate
  - llvm-hs-pretty
  - llvm-hs-pure
  - megaparsec
  - mtl
  - optparse-applicative
  - parsec
  - parser-combinators
  - pretty
  - pretty-simple
  - string-conversions
  - text
  - transformers
  - vector
  - optics

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wno-name-shadowing
  - -j4
  - +RTS -A128m -n2m -qg -RTS

default-extensions:
  - StrictData

library:
  source-dirs: src