name: Generate CHANGELOG.md

on:
  push:
    branches:
      - master

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose a65e09d..HEAD
        env:
          OUTPUT: CHANGELOG.md
      - name: Check if there are any changes
        id: check_changes
        run: |
          git add -N .
          git diff --exit-code
        continue-on-error: true
      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "generate changelog"
          git push
        if: steps.check_changes.outcome == 'failure'