name: Generate CHANGELOG.md

on:
  push:
    branches:
      - master

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install git-cliff
        run: |
          cargo install git-cliff
      - name: Generate CHANGELOG.md
        run: |
          sh ./scripts/changelog.sh > CHANGELOG.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push
