name: Kagami CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libgc-dev llvm-9-dev
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.2'
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: |
        stack install hspec-discover --overwrite-policy=always
        export PATH=~/.stack/bin:$PATH

    - name: Build
      run: |
        stack build
    - name: Run tests
      run: |
        ./test_malgo.sh
        ./test_griff.sh
