name: Malgo CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.0.2']
        os: [ubuntu-latest]
      # fail-fast: true

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libgc-dev llvm-9-dev
    - uses: actions/checkout@v2
    - name: Cache .cabal
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
          v0.2/dist-newstyle
          ~/.stack
          v0.2/.stack-work
        key: ${{ runner.os }}-build-${{ hashFiles('v0.2/package.yaml', 'v0.2/stack.yaml') }}
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'
        # cabal-version: '3.2.0.0'
    - name: GHC ${{matrix.ghc}} Build
      run: |
        cd v0.2/
        stack build
    - name: Run tests
      run: |
        mkdir -p $HOME/.local/share/malgo/base
        cd v0.2/
        ./scripts/install_malgo_internal.sh
        ./scripts/pretest.sh stack
        stack test
