name: Malgo CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libgc-dev llvm-9-dev
    - uses: actions/checkout@v2
    - name: Cache .cabal
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
          dist-newstyle
        key: ${{ runner.os }}-build-${{ hashFiles('malgo/malgo.cabal', 'koriel/koriel.cabal', 'cabal.project.freeze') }}
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
        # cabal-version: '3.2.0.0'
    - name: Build
      run: |
        cabal build all
    - name: Run tests
      run: |
        mkdir -p $HOME/.local/share/malgo/base
        ./scripts/install_malgo_internal.sh
        ./scripts/test_malgo_parallel.sh
