name: Malgo CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.6.2"]
        os: [ubuntu-latest]

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
      - uses: actions/checkout@v2
      - name: Cache .cabal
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - uses: haskell/actions/setup@v2
        with:
          ghc-version:
            ${{ matrix.ghc }}
          cabal-version: "3.10.1.0"
      - name: Install dependencies
        run: |
          cabal build --only-dependencies
      - name: GHC ${{matrix.ghc}} Build
        run: |
          stack build
      - name: Run tests
        run: |
          stack test
