name: Malgo CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.6.4"]
        os: [ubuntu-latest]

    steps:
      - name: add llvm repo
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main
          repo-name: llvm
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgc-dev
          sudo apt-get install -y llvm-15-dev clang-15
      - uses: actions/checkout@v4
      - name: Cache .cabal
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - uses: haskell-actions/setup@v2
        with:
          ghc-version:
            ${{ matrix.ghc }}
          cabal-version: "3.10.1.0"
      - name: Install dependencies
        run: |
          cabal build --only-dependencies
      - name: GHC ${{matrix.ghc}} Build
        run: |
          cabal build
      - name: Run tests
        id: run-tests
        run: |
          cabal test --test-show-details=direct --test-option='--skip=llvm'
        continue-on-error: true
      - name: Upload .golden
        uses: actions/upload-artifact@v4
        with:
          name: golden
          path: .golden/
      - name: Error handling
        if: ${{ steps.run-tests.outcome == 'failure' }}
        run: exit 1