name: Malgo CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.2.4"]
        os: [ubuntu-latest]
      # fail-fast: true

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libgc-dev llvm-12-dev
      - uses: actions/checkout@v2
      - name: Cache .cabal
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - uses: haskell/actions/setup@v2
        with:
          ghc-version:
            ${{ matrix.ghc }}
            # enable-stack: true
            # stack-version: 'latest'
          cabal-version: "3.6.2.0"
      - name: GHC ${{matrix.ghc}} Build
        run: |
          cabal build
      - name: Run tests
        run: |
          mkdir -p $HOME/.local/share/malgo/base
          ./scripts/install_malgo_internal.sh
          ./scripts/pretest.sh cabal
          cabal test
