name: SBOM upload

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  SBOM-upload:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Generate SBOM
      run: |
        curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b $RUNNER_TEMP
        $RUNNER_TEMP/syft scan dir:./ -o spdx-json=sbom.spdx.json
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: sbom
        path: sbom.spdx.json
    - name: SBOM upload
      uses: advanced-security/spdx-dependency-submission-action@8b97fad313c1af2c5c490e1f72ab338371eb92f6 # v0.3.2
